### ISSUE TITLE
Does it possible run it with npm-script?

### ISSUE THREAD

**Issue by fireflyEngineer** [nearform/node-clinic-flame#101]
I used it with babel-node and some other arguments, But  got
```
error Command "-r" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Debugged the source code and found
```
  spawnargs:
   [ 'yarn',
     '--prof',
     '--logfile=%p-v8.log',
     '--print-opt-source',
     '-r',
     '/Users/firefly/.config/yarn/global/node_modules/0x/lib/preload/no-cluster',
     '-r',
     '/Users/firefly/.config/yarn/global/node_modules/0x/lib/preload/redir-stdout',
     '-r',
     '/Users/firefly/.config/yarn/global/node_modules/0x/lib/preload/soft-exit',
     'perfServer' ],
```
It Maybe only fit node command.

**Comment by goto-bus-stop** [comment]
Yeah, that's correct, Flame and 0x (the module Flame uses for performance measuring) only work with explicit `node` commands right now.

FWIW, using babel-node is likely to yield poor results because Flame will record all the time Babel spends transforming your code as well. If possible I'd recommend doing any source transformations _first_, and then running Flame with the final output.

**Comment by davidmarkclements** [comment]
I think you can do  `clinic flame -- node ./node_modules/.bin/babel-node app.js` ... you can definitely do  `0x -- node ./node_modules/.bin/babel-node app.js`

**Comment by fireflyEngineer** [comment]
Yeah i get it, thanks.
