### ISSUE TITLE
Cannot read property 'onStackTop' of undefined

### ISSUE THREAD

**Issue by cuginoAle** [nearform/node-clinic-flame#16]
- On load open the option drop-down
- Uncheck all the options in `Visibility by code area`

<img width="833" alt="screenshot 2018-11-05 at 20 30 46" src="https://user-images.githubusercontent.com/1298616/48021999-3c404d80-e13a-11e8-9b1b-dfd1251cd7b2.png">

**Comment by goto-bus-stop** [comment]
Started working on a fix for this but there are maaany places that assume we have data :smile: It's turning out to be quite tricky…!

**Comment by AlanSl** [comment]
Known causes:

- [ ] Excluding all nodes: being fixed in https://github.com/nearform/node-clinic-flame/pull/56
- [ ] Excluding the currently zoomed and selected node: appears to have been a regression in an earlier PR that was straightened out as a side effect of https://github.com/nearform/node-clinic-flame/pull/39
- [ ] Whatever caused https://github.com/nearform/node-clinic-flame/issues/54 - this appears to be completely different to the others, need more info to fix

**Comment by cuginoAle** [comment]
After some tests the first scenario describe by @AlanSl  (`Excluding all nodes`) is the only one I can use to replicate the error
